"""followers

Revision ID: 964da6e471ce
Revises: 7cc4c6d51909
Create Date: 2019-09-22 16:29:16.790531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964da6e471ce'
down_revision = 'f43b9e4346d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
